# Simple Neural Network in Numpy

In [1]:
# import modules
import numpy as np

In [2]:
# helper function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [3]:
#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

In [4]:
#Variable initialization
inputlayer_neurons = 4 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))

wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [5]:
print('Initial weights','\n',  wh, '\n\n', 'Initial biases', bh)

Initial weights 
 [[ 0.7311026   0.98071962  0.08096642]
 [ 0.71554855  0.89738158  0.04193665]
 [ 0.83022163  0.15372335  0.59566082]
 [ 0.58744679  0.73600899  0.48125201]] 

 Initial biases [[ 0.14637286  0.11912364  0.4527222 ]]


In [6]:
## Forward Propogation

# linear transformation
hidden_layer_input1=np.dot(X,wh)
hidden_layer_input=hidden_layer_input1 + bh
# non-linear transformation
hiddenlayer_activations = sigmoid(hidden_layer_input)

# linear transformation
output_layer_input1=np.dot(hiddenlayer_activations,wout)
output_layer_input= output_layer_input1+ bout
# non-linear transformation
output = sigmoid(output_layer_input)

In [7]:
print('Weights after forward propogation','\n',  wh, '\n\n', 'Biases after forward propogation', bh)

Weights after forward propogation 
 [[ 0.7311026   0.98071962  0.08096642]
 [ 0.71554855  0.89738158  0.04193665]
 [ 0.83022163  0.15372335  0.59566082]
 [ 0.58744679  0.73600899  0.48125201]] 

 Biases after forward propogation [[ 0.14637286  0.11912364  0.4527222 ]]


In [8]:
## Backpropagation

# error at output
E = y - output

slope_output_layer = derivatives_sigmoid(output)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
d_output = E * slope_output_layer

# error at hidden layer
Error_at_hidden_layer = d_output.dot(wout.T)
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

# weight update at output layer
wout += hiddenlayer_activations.T.dot(d_output) *0.1
bout += np.sum(d_output, axis=0,keepdims=True) *0.1

# weight update at hidden layer
wh += X.T.dot(d_hiddenlayer) *0.1
bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *0.1

In [9]:
print('Updated weights','\n',  wh, '\n\n', 'Updated biases', bh)

Updated weights 
 [[ 0.7311539   0.98100047  0.08126635]
 [ 0.71526267  0.89640536  0.04050067]
 [ 0.83027293  0.1540042   0.59596075]
 [ 0.58717784  0.73512269  0.4799259 ]] 

 Updated biases [[ 0.14613828  0.11842827  0.45158615]]


In [10]:
print('Actual', y, '\n\n', 'Predictions', output, '\n\n', 'Error', E.sum())

Actual [[1]
 [1]
 [0]] 

 Predictions [[ 0.87746235]
 [ 0.89351924]
 [ 0.88086316]] 

 Error -0.651844754228


In [11]:
# after 5000 iterations
for i in range(5000):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) * 0.1
    bout += np.sum(d_output, axis=0,keepdims=True) * 0.1
    wh += X.T.dot(d_hiddenlayer) * 0.1
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) * 0.1

In [12]:
print('Updated weights','\n',  wh, '\n\n', 'Updated biases', bh)

Updated weights 
 [[-0.07297633  1.51520053  1.85924922]
 [ 1.40964956 -0.19864931 -2.42763612]
 [ 0.0261427   0.68820426  2.37394362]
 [ 0.86271232 -0.09176732 -0.85381179]] 

 Updated biases [[ 0.03639495 -0.44242634 -0.23856778]]


In [13]:
print('Actual', y, '\n\n', 'Predictions', output, '\n\n', 'Error', E.sum())

Actual [[1]
 [1]
 [0]] 

 Predictions [[ 0.97887545]
 [ 0.96472972]
 [ 0.04860712]] 

 Error 0.00778771257289
